### ISSUE TITLE
mod_quality_overview tests fail on linux

### ISSUE THREAD

**Issue by arnfinn** [mong/qmongr#143]
mod_quality_overview tests fail on linux and Travis has started failing because of this.

Seems like `role="presentation" aria-label="circle-o icon"` is added (see example diff below).

```diff
+++ b/tests/testthat/data/output_qi_table_bergen_2019.html
@@ -37,7 +37,7 @@
         <div class="level">
           <h3>
             46%
-            <i class="fa fa-circle-o low"></i>
+            <i class="fa fa-circle-o low" role="presentation" aria-label="circle-o icon"></i>
           </h3>
         </div>
         <div class="ones_of_total">
```

Started failing July 11 (https://travis-ci.org/github/mong/qmongr/builds)

Probably not related, but some differences between July 10 and July 11:

```
rlang (0.4.6 -> 0.4.7) [CRAN]
pillar (1.4.4 -> 1.4.6) [CRAN]
tibble (3.0.2 -> 3.0.3) [CRAN]
```

**Comment by yte0** [comment]
It is caused by an update in shiny

**Comment by yte0** [comment]
![Skjermbilde](https://user-images.githubusercontent.com/54272616/88069541-e1e75a80-cb71-11ea-92d3-9addbede256f.PNG)

**Comment by arnfinn** [comment]
I will send a PR soon where we use the new cran version of shiny. Might help.

**Comment by yte0** [comment]
i have update the the tests, that might do it for now

**Comment by arnfinn** [comment]
Great!
