### ISSUE TITLE
Fedora: not able to log into adminer

### ISSUE THREAD

**Issue by arnfinn** [mong/qmongr#158]
On Fedora:

1. download `imongr_db_dump.sql.gz`
2. `docker-compose up`
3. Go to http://localhost:8888/ and log in with username and password `imongr`:

![Screenshot from 2020-08-21 14-42-06](https://user-images.githubusercontent.com/136346/90891812-987e6b00-e3bc-11ea-83bd-61b8d5ff8f1e.png)

**Comment by areedv** [comment]
Can you connect by ```mariadb -h db -u imongr -p*****``` from a console inside the container?
