### ISSUE TITLE
App will break if data with orgnr 111111111

### ISSUE THREAD

**Issue by arnfinn** [mong/qmongr#170]
In other words it will break if there is data for two different countries ("Nasjonalt" and "Udefinerte land" at the moment).

**Comment by areedv** [comment]
This is not at bug in qmongr but rather so in our org model. After updating the org hierarchy, re-aggregate all data

**Comment by arnfinn** [comment]
The app will break if someone delivers data with orgnr 111111111, as long as it is at the same level as orgnr 1. So we have to delete 111111111 from the db to be sure that this will not happen. FYI, I just did that.
