### ISSUE TITLE
Filtrer ut sykehus som ikke har data siste fire år

### ISSUE THREAD

**Issue by arnfinn** [mong/qmongr#171]
Kysthospitalet i Hagevik har for eksempel noen få data i Hoftebruddregisteret der de nyeste er tilbake i 2013. Kysthospitalet i Hagevik vil derfor dukke opp i valg av sykehus, men data fra sykehuset vil aldri kunne vises i appen. Der vises kun sykehus som har data fra 2016 og fremover.

Sykehus som ikke har data som kan vises i appen burde derfor filtreres ut før de lastes opp til nettleser. Vil også kunne gjelde sykehus med kun lave tall, som uansett vil måtte filtreres ut.

**Comment by areedv** [comment]
In other words: remove data older than 4 years...

**Comment by arnfinn** [comment]
No:) We want to keep older data for hospitals present in newer data, to get nice time trend figure.

**Comment by areedv** [comment]
I see. And fix
