### ISSUE TITLE
Opprette QA-miljø

### ISSUE THREAD

**Issue by arnfinn** [mong/qmongr#184]
## Hva

Opprette QA-miljø for å kunne kontrollere at nye versjoner av sykehusviseren på kvalitetsregister.no fungerer.

## Hvorfor

Siden vi driver med CD (kontinuerlig levering) vil det stadig komme nye versjoner av sykehusviseren ut på det vide vev. Å kontrollere at ny versjon er ok må kunne gjøres enkelt.

### Forslag til løsning

Lager en nettside tilsvarende https://mongr.no/app/qmongr som lukter på `hnskde/qmongr:master` i stedet for `hnskde/qmongr:latest`, og bygger denne. `hnskde/qmongr:master` er et docker image som bygges for hver ny commit til `master`-greina av `qmongr`. `hnskde/qmongr:latest` er et docker image som bygges for hver ny release tag til `qmongr`.

### Forslag til løsning 2

...

**Comment by arnfinn** [comment]
Related issue: https://github.com/mong/shinyproxy/issues/3

**Comment by areedv** [comment]
Forslaget til løsning er godt, syns jeg. Vi må da ha en ny _app-context_ på (spring boot) mongr.no ala måten imongr er satt opp på. På sikt burde da også qmongr få en egen _app-context_ for å ivareta konsistens, men det er spørs om det er lurt å gjøre så mange endringer på qmongr nå...

**Comment by areedv** [comment]
Denne saken løser ikke utfordringen med (test av) datainnlesing og aggregering, noe som bør tas i en et eget tiltak/sak

**Comment by areedv** [comment]
Denne saken utsettes til etter "lansering". Foreløpig fix for de som trenger det er å benytte vårt utviklingsmiljø (med oppdaterte) data lokalt (docker)

**Comment by arnfinn** [comment]
Fikset for `qmongjs`, på `aws`.
