### ISSUE TITLE
Is it possible to enable bookmarking?

### ISSUE THREAD

**Issue by arnfinn** [mong/qmongr#66]
https://shiny.rstudio.com/reference/shiny/latest/enableBookmarking.html

I guess `url` is easy, but `server` not possible with *shinyproxy*?

**Comment by areedv** [comment]
A docker container can mount host storage persisting data beyond the container lifetime. Hence `server` should be ok. Why do we want to use bookmarking?

**Comment by arnfinn** [comment]
Not completely sure why I wanted it. Maybe I was thinking that it could be a way of the main page to interact with the qmongr app inside an iframe.

**Comment by arnfinn** [comment]
Enabled in #217
