### ISSUE TITLE
Split mod_quality_overview_server into modules?

### ISSUE THREAD

**Issue by arnfinn** [mong/qmongr#91]
The complexity is increasing for every new PR:)

**Comment by arnfinn** [comment]
@areedv @yte0

**Comment by areedv** [comment]
I've used my last pr to get into the actual code of qmongr. What strikes me as the most difficult is the test layout. For a start it would be quite useful if messages describes WHAT is being tested. Just from
```test_that("mod_quality_overview_ui", {```
it is not possible to understand what is being tested. It is actually meant to be a sentence, _e.g_ "[Test that] the ui conforms to a stored/static state". And, testing has no value _per se_; a coverage of 80% does not mean that the app has less of a value of being semi broken :-). Further, it is not obvious what steps to take (files to update) when adding new code or config in order for tests to work they way they should.

I'm not quite into shiny modules but my initial expectation is that modules are a way to avoid complexity when app code grows. If a module becomes too long/complex it might benefit from refactoring into several modules. Yet, in my opinion, qmongr is still not a particularly large stack of code...

**Comment by arnfinn** [comment]
I totally agree that our test layout is not top notch:)  

I think we should write documentation inside the test functions, where we explain what is tested and why. Maybe we also should split the tests into several `test_that(` sections with more descriptive text? But I have to (partly) disagree with this:
> For a start it would be quite useful if messages describes WHAT is being tested. Just from `test_that("mod_quality_overview_ui", {` it is not possible to understand what is being tested.

If `mod_quality_overview_ui` fails I know it is the function `mod_quality_overview_ui` that is failing (or something related to that function). For instance with this failure:
```
test-mod_quality_overview.R:163: failure: mod_quality_overview_ui
grepl(config$app_text$indicators$high, c("tmp"), fixed = TRUE) isn't true.
```
I know where to start looking.

With `test_that("the ui conforms to a stored/static state", {` and this output:
```
test-mod_quality_overview.R:163: failure: the ui conforms to a stored/static state
grepl(config$app_text$indicators$high, c("tmp"), fixed = TRUE) isn't true.
```
I do not know where to look for bugs.

**Comment by yte0** [comment]
I think most of the effort so far has been aimed towards getting something up and running.  Going forward as more and more of the puzzle pieces fall in place, a larger share of our time can go towards cleaning up the code, bettering the documentation and improving the effieciency. I think we have a good platform right now, with a potential for further improvment.  

More of the code in the server module can also be moved out and placed in separate  functions/ modules. Not sure what the gain of more shiny modules in the mod_quality_overview_server is right now.

**Comment by arnfinn** [comment]
I prefer that we "write functions that do one thing and do it well" (part of the Unix philosophy):) Then
- We can work in different places of the app without making conflicts.
- We can create clear API between the functions/modules, so we do not have to worry about the internal stuff in each module.
- It is much easier to unit test (with a clear API).

The way it is now we have to run the whole app when testing (the app is one module). It also means that if one part of the module is broken then all the (module) tests will fail. Besides, almost all the tests will fail if `qmongrdata` is changed, since `load_data()` will run in every test of the module.

**Comment by arnfinn** [comment]
Started with a chart/scheme here:

![scheme](https://user-images.githubusercontent.com/136346/77086449-19969800-6a02-11ea-82ec-44ceac348bea.png)

Did not think about input yet. OK?
