### ISSUE TITLE
Move qmongr repository to mong

### ISSUE THREAD

**Issue by arnfinn** [mong/qmongr#99]
The transfer in itself is easy (push a button).

# To do before the move

- Decide if we want to move or not. **Please cast your vote below!**

# To do after the move

- [x] Replace all occurrences of `SKDE-Felles` in the code
- [x] Make sure all the external services work
  - [x] Travis CI
  - [x] Appveyor
  - [x] codecov
  - [x] Docker hub
- [ ] Make sure new versions end up on mongr.no
- [ ] ...

# To do on your machine after the move

```
git remote set-url origin git@github.com:mong/qmongr
```

or if you are behind proxy:
```
git remote set-url origin githubhn:mong/qmongr
```

**Comment by areedv** [comment]
Yea

**Comment by arnfinn** [comment]
BTW, I transferred tabellverk-repository from `SKDE-Analyse` to `mong` the other day, with no problems (and renamed it from `dynamiskTabellverk` to `tmongr`). Issues and everything were also transferred.

**Comment by areedv** [comment]
Moved _shinyproxy_, _lb-rp_ and _qmongr-base-r_

**Comment by arnfinn** [comment]
Moved *qmongr*...

**Comment by arnfinn** [comment]
We moved...
